# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='padrereuniones',
        ),
        migrations.RemoveField(
            model_name='temasdos',
            name='tema_padre',
        ),
        migrations.AlterField(
            model_name='reuniones',
            name='idEstado',
            field=models.CharField(blank=True, default='Citacion', max_length=2, null=True, verbose_name='Estado Reunion'),
        ),
        migrations.DeleteModel(
            name='EstadoReunion',
        ),
    ]
